Repository fisher60/friendo-bot, pull requests merged in 2020-10, with the labels that each got.

#58 converted the user input to lowercase so phrase will always alternate
  bot/cogs/fun.py
Labels: bug

#66 Refactoring the "develop" branch.
  Pipfile
  Pipfile.lock
  bot/__init__.py
  bot/__main__.py
  bot/bot.py
  bot/cogs/memes.py
  bot/meme_api/memegen.py
  bot/settings.py
  bot/start.py
Labels: Hacktoberfest, enhancement, priority: high

#77 Trivia Commands Addition
  bot/__main__.py
  bot/cogs/trivia.py
  bot/cogs/weather.py
Labels: enhancement

#128 Disabling of certain cogs based on command line arguments
  README.md
  bot/bot.py
  bot/disable.py
  bot/settings.py
Labels: hacktoberfest-accepted

#130 Finished Trivia Leaderboard
  bot/cogs/trivia.py
Labels: hacktoberfest-accepted

#127 Logging setup
  .gitignore
  bot/__init__.py
  bot/bot.py
  bot/cogs/admin.py
  bot/cogs/events.py
  bot/cogs/fun.py
  bot/cogs/list_of_quotes.py
  bot/cogs/todo_list.py
  bot/cogs/utilities.py
  bot/events_api/__init__.py
  bot/meme_api/memegen.py
  bot/settings.py
Labels: hacktoberfest-accepted

#142 Refactoring the entire bot.
  .flake8
  .github/workflows/greetings.yml
  .github/workflows/linting.yml
  .gitignore
  .pre-commit-config.yaml
  Pipfile
  bot/__init__.py
  bot/__main__.py
  bot/bot.py
  bot/cogs/__init__.py
  bot/cogs/admin.py
  bot/cogs/covid_stats.py
  bot/cogs/events.py
  bot/cogs/fun.py
  bot/cogs/greetings.py
  bot/cogs/help.py
  bot/cogs/image_segmentation.py
  bot/cogs/list_of_quotes.py
  bot/cogs/memes.py
  bot/cogs/randomcase.py
  bot/cogs/source.py
  bot/cogs/todo_list.py
  bot/cogs/trivia.py
  bot/cogs/utilities.py
  bot/cogs/weather.py
  bot/disable.py
  bot/events_api/__init__.py
  bot/image_cache/.gitkeep
  bot/meme_api/memegen.py
  bot/resources/greetings.yaml
  bot/resources/list_of_quotes.yaml
  bot/save_data.JSON
  bot/settings.py
  bot/todo_list_data.json
  docker-compose.yml
Labels: Hacktoberfest, enhancement, priority: regular
