Repository fisher60/friendo-bot, pull requests merged in 2020-09, with the labels that each got.

#10 Clean up project and development dependencies
  Pipfile
  Pipfile.lock
Labels: enhancement

#29 Feature: alternating case
  bot/__main__.py
  bot/cogs/fun.py
Labels: enhancement

#36 Fix: Pipenv Readme instructions
  README.md
Labels: bug

#39 feature eight ball
  bot/cogs/fun.py
Labels: enhancement

#27 Feature: `pre-commit` hooks
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  README.md
Labels: enhancement, priority: immediate

#54 Feature/image segmentation
  .gitignore
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/cogs/image_segmentation.py
  bot/image_cache/.gitkeep
  bot/image_cache/temp_img_0.jpg
  bot/settings.py
  bot/start.py
Labels: enhancement
