Repository fisher60/friendo-bot, pull requests merged in 2022-10, with the labels that each got.

#237 add restart: always to docker-compose. This ensures the bot will rebo…
  docker-compose.yml
Labels: hacktoberfest-accepted

#241 remove graphql response api token from logging
  bot/graphql.py
Labels: priority: immediate, hacktoberfest-accepted, security

#255 Use the same session for the bot and graphql
  Dockerfile
  bot/__init__.py
  bot/__main__.py
  bot/bot.py
  bot/cogs/admin.py
  bot/cogs/advent_of_code.py
  bot/cogs/fun.py
  bot/cogs/greetings.py
  bot/cogs/image_segmentation.py
  bot/cogs/pixelate.py
  bot/cogs/timezone_tracker.py
  bot/cogs/todo_list.py
  bot/cogs/user.py
  bot/cogs/utilities.py
  bot/cogs/wolfram.py
  bot/cogs/wonder_twins.py
  bot/graphql.py
  bot/meme_api/memegen.py
  bot/settings.py
Labels: enhancement, priority: regular, hacktoberfest-accepted
